version: '2.2'
services:
  mumbler:
    build: .
    mem_limit: 1G
    memswap_limit: 1G
    pids_limit: 20
    network_mode: host

    ulimits:
      nofile:
        soft: 15000
        hard: 15000

    volumes:
      - ./storage:/app/storage
    restart: always
    stop_grace_period: 10s
