version: '2.2'

services:
  postgres:
    image: postgres:13.1-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: on-failure
    stop_grace_period: 10s
    mem_limit: 1G
    memswap_limit: 1G
    pids_limit: 100

  web:
    build: .
    restart: on-failure
    stop_grace_period: 10s
    depends_on:
      - postgres
    ports:
      - "3113:3113"
    ulimits:
      nofile:
        soft: 12000
        hard: 12000
    mem_limit: 1G
    memswap_limit: 1G
    pids_limit: 100
