version: '2.2'

services:
  trackserver:
    build:
      context: .
      dockerfile: Dockerfile-trackserver
    restart: always
    ports:
      - 12345:12345
    depends_on:
      - cassandra
    pids_limit: 100
    mem_limit: 1G
    memswap_limit: 1G
    ulimits:
      nofile:
        soft: 12000
        hard: 12000

  web:
    build:
      context: .
      dockerfile: Dockerfile-web
    restart: always
    ports:
      - 7000:7000
    depends_on:
      - cassandra
    pids_limit: 100
    mem_limit: 1G
    memswap_limit: 1G
    ulimits:
      nofile:
        soft: 12000
        hard: 12000

  cassandra:
    image: cassandra:3.11.9
    restart: always
    environment:
      - MAX_HEAP_SIZE=512M
      - HEAP_NEWSIZE=512M
    volumes:
      - ./data:/var/lib/cassandra
    pids_limit: 200
    mem_limit: 2G
    memswap_limit: 2G
    ulimits:
      nofile:
        soft: 12000
        hard: 12000
