
name: Check keeper
on:
  push:
    branches:
      - main
    paths:
      - 'services/keeper/**'
      - 'checkers/keeper/**'
  workflow_dispatch: {}

jobs:
  check_services:
    name: Check keeper
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Setup keeper
      run: (cd ./services/keeper && docker-compose pull && docker-compose build && docker-compose up --build -d)

    - name: Prepare python for checker
      uses: actions/setup-python@v2
      with:
        python-version: 3.8.5

    - name: Setup checker libraries
      run: if [ -f checkers/keeper/requirements.txt ]; then python -m pip install -r checkers/keeper/requirements.txt; fi

    - name: Test checker on service
      run: checkers/keeper/checker.py TEST 127.0.0.1

