
name: Check mumbler
on:
  push:
    branches:
      - main
    paths:
      - 'services/mumbler/**'
      - 'checkers/mumbler/**'
  workflow_dispatch: {}

jobs:
  check_mumbler:
    name: Check mumbler
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Setup mumbler
      run: (cd ./services/mumbler && docker-compose pull && docker-compose build && docker-compose up --build -d)

    - name: Prepare python for checker
      uses: actions/setup-python@v2
      with:
        python-version: 3.8.5

    - name: Setup checker libraries
      run: if [ -f checkers/mumbler/requirements.txt ]; then python -m pip install -r checkers/mumbler/requirements.txt; fi

    - name: Test checker on service
      run: checkers/mumbler/checker.py TEST 127.0.0.1
  update_mumbler:
    name: Deploy service using ansible to first teams
    needs: check_mumbler
    runs-on: ubuntu-18.04

    steps:
    - name: install ansible
      run: sudo apt-get install -y ansible

    - name: Checkout repo
      uses: actions/checkout@v2

    - name: try to deploy mumbler
      run: ./vuln_image/update_first_ten_teams.sh mumbler

