
name: Check sesame
on:
  push:
    branches:
      - main
    paths:
      - 'services/sesame/**'
      - 'checkers/sesame/**'
  workflow_dispatch: {}

jobs:
  check_sesame:
    name: Check sesame
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Setup sesame
      run: (cd ./services/sesame && docker-compose pull && docker-compose build && docker-compose up --build -d)

    - name: Prepare python for checker
      uses: actions/setup-python@v2
      with:
        python-version: 3.8.5

    - name: Setup checker libraries
      run: if [ -f checkers/sesame/requirements.txt ]; then python -m pip install -r checkers/sesame/requirements.txt; fi

    - name: Test checker on service
      run: checkers/sesame/checker.py TEST 127.0.0.1
  update_sesame:
    name: Deploy service using ansible to first teams
    needs: check_sesame
    runs-on: ubuntu-18.04

    steps:
    - name: install ansible
      run: apt-get install -y ansible

    - name: Checkout repo
      uses: actions/checkout@v2

    - name: try to deploy sesame
      run: ./vuln_image/update_first_ten_teams.sh sesame

