
name: Check carpetradar24
on:
  push:
    branches:
      - main
    paths:
      - 'services/carpetradar24/**'
      - 'checkers/carpetradar24/**'
  workflow_dispatch: {}

jobs:
  check_services:
    name: Check carpetradar24
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Setup carpetradar24
      run: (cd ./services/carpetradar24 && docker-compose pull && docker-compose build && docker-compose up --build -d)

    - name: Prepare python for checker
      uses: actions/setup-python@v2
      with:
        python-version: 3.8.5

    - name: Setup checker libraries
      run: if [ -f checkers/carpetradar24/requirements.txt ]; then python -m pip install -r checkers/carpetradar24/requirements.txt; fi

    - name: Test checker on service
      run: checkers/carpetradar24/checker.py TEST 127.0.0.1

